config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :loans
  match 'loans/:id', controller: 'loans', action: 'devolver', via: 'post'
  resources :authorizations
  resources :rooms
  resources :users

  root 'loans#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :authorizations, :dependent => :restrict_with_exception
  has_many :loans, :dependent => :restrict_with_exception
  
  validates_presence_of :title
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_filter :authorize, only: [:index]
  before_action :usuario_comum
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all.paginate(page: params[:page], per_page: 15)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Sala criada.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_path, notice: 'Sala editada.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    begin
      @room.destroy
      respond_to do |format|
        format.html { redirect_to rooms_url, notice: 'Sala apagada.' }
        format.json { head :no_content }
      end
    rescue
      redirect_to rooms_url, notice: 'Ação interrompida - Esta sala possui dependências.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Nome %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Localização %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Confirmar', class: "btn btn-default btnlogin" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div id="form_criacao">
<h1>Editando Salas</h1>

<%= render 'form' %>

<%= link_to 'Voltar', rooms_path, class: "btn btn-sm btn-default" %>
</div>

app/views/rooms/index.html.erb
<h1>Listando Salas</h1>
<%= will_paginate @rooms %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Localização</th>
      <th colspan="2" id="btn_novo"><%= link_to 'Nova Sala', new_room_path, class: "btn btn-block btn-success" %></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.order(title: :asc).each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.location %></td>
        <td id="coluna_novo"><%= link_to 'Editar', edit_room_path(room), class: "btn btn-sm btn-default" %></td>
        <td id="coluna_novo"><%= link_to 'Apagar', room, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-sm btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @rooms %>

app/views/rooms/new.html.erb
<div id="form_criacao">
<h1>Nova Sala</h1>

<%= render 'form' %>

<%= link_to 'Voltar', rooms_path, class: "btn btn-sm btn-default" %>
</div>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>