config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :loans
  match 'loans/:id', controller: 'loans', action: 'devolver', via: 'post'
  resources :authorizations
  resources :rooms
  resources :users

  root 'loans#index'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  belongs_to :authorizer, :class_name => 'User'
  belongs_to :room

  validates_presence_of :user_id, :authorizer_id, :room_id, :date_register, :date_expiration

  scope :ativos, ->{ where('date_expiration >= ?', Time.now) }
  scope :expirados, ->{ where('date_expiration < ?', Time.now) }

end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  skip_before_filter :authorize, only: [:index]
  before_action :usuario_comum
  before_action :set_authorization, only: [:show, :edit, :update, :destroy]

  # GET /authorizations
  # GET /authorizations.json
  def index
    @authorizations = Authorization.all
  end

  # GET /authorizations/1
  # GET /authorizations/1.json
  def show
  end

  # GET /authorizations/new
  def new
    @authorization = Authorization.new
  end

  # GET /authorizations/1/edit
  def edit
  end

  # POST /authorizations
  # POST /authorizations.json
  def create
    @authorization = Authorization.new(authorization_params)
    @authorization.date_register = Date.today

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to authorizations_path, notice: 'Autorização criada.' }
        format.json { render :show, status: :created, location: @authorization }
      else
        format.html { render :new }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorizations/1
  # PATCH/PUT /authorizations/1.json
  def update
    respond_to do |format|
      if @authorization.update(authorization_params)
        format.html { redirect_to authorizations_path, notice: 'Autorização editada.' }
        format.json { render :show, status: :ok, location: @authorization }
      else
        format.html { render :edit }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization.destroy
    respond_to do |format|
      format.html { redirect_to authorizations_url, notice: 'Autorização apagada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorization
      @authorization = Authorization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorization_params
      params.require(:authorization).permit(:user_id, :authorizer_id, :room_id, :date_register, :date_expiration)
    end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_form.html.erb
<%= form_for(@authorization) do |f| %>
  <% if @authorization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorization.errors.count, "error") %> prohibited this authorization from being saved:</h2>

      <ul>
      <% @authorization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user_logado.admin %>
    <div class="form-group">
      <%= f.label :Autorizador %><br>
      <%= f.collection_select :authorizer_id, User.servidores.order(:nome),:id,:nome_matricula, {include_blank: true}, {class: "form-control"} %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :Autorizador %><br>
      <%= f.collection_select :authorizer_id,
          User.servidores.order(:nome),:id,:nome_matricula,
          {selected: @user_logado.id},
          {class: "form-control", :disabled => "disabled"} %>
      <%= f.hidden_field :authorizer_id, :value => @user_logado.id %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :Aluno %><br>
    <%= f.collection_select :user_id, User.alunos.order(:nome),:id,:nome_matricula, {include_blank: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :Sala %><br>
    <%= f.collection_select :room_id, Room.order(:title),:id,:title, {include_blank: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label 'Vencimento' %><br>
    <%= f.date_select :date_expiration,
        :order => [:day, :month, :year],
        :start_year => Date.today.year,
        :end_year => Date.today.year + 1,
        :html=>{:class => "form-control"}%>
  </div>
  <div class="form-group">
    <%= f.submit 'Confirmar', class: "btn btn-default btnlogin" %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<div id="form_criacao">
<h1>Editando Autorização</h1>

<%= render 'form' %>

<%= link_to 'Voltar', authorizations_path, class: "btn btn-sm btn-default" %>
</div>

app/views/authorizations/index.html.erb
<h1>Listando Permissões Ativas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Professor</th>
      <th>Aluno</th>
      <th>Sala</th>
      <th>Data do Registro</th>
      <th>Vencimento</th>
      <th colspan="2" id="btn_novo"><%= link_to 'Nova Permissão', new_authorization_path, class: "btn btn-block btn-success" %></th>
    </tr>
  </thead>

  <tbody>
    <% @authorizations.ativos.each do |authorization| %>
      <tr>
        <td><%= authorization.authorizer.nome %></td>
        <td><%= authorization.user.nome %></td>
        <td><%= authorization.room.title %></td>
        <td><%= authorization.date_register.strftime("%d/%m/%Y") %></td>
        <td><%= authorization.date_expiration.strftime("%d/%m/%Y") %></td>
        <% if authorization.authorizer == @user_logado or @user_logado.admin %>
        <td id="coluna_novo"><%= link_to 'Editar', edit_authorization_path(authorization), class: "btn btn-sm btn-default" %></td>
        <td id="coluna_novo"><%= link_to 'Apagar', authorization, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-sm btn-default" %></td>
        <% else %>
          <td id="coluna_novo"><td>
          <td id="coluna_novo"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Listando Permissões expiradas</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Professor</th>
      <th>Aluno</th>
      <th>Sala</th>
      <th>Data do Registro</th>
      <th>Vencimento</th>
    </tr>
  </thead>

  <tbody>
    <% @authorizations.expirados.last(35).each do |authorization| %>
      <tr>
        <td><%= authorization.authorizer.nome %></td>
        <td><%= authorization.user.nome %></td>
        <td><%= authorization.room.title %></td>
        <td><%= authorization.date_register.strftime("%d/%m/%Y") %></td>
        <td><%= authorization.date_expiration.strftime("%d/%m/%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authorizations/new.html.erb
<div id="form_criacao">
<h1>Nova Autorização</h1>

<%= render 'form' %>

<%= link_to 'Voltar', authorizations_path, class: "btn btn-sm btn-default" %>
</div>

app/views/authorizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professor:</strong>
  <%= @authorization.authorizer.nome %>
</p>

<p>
  <strong>User:</strong>
  <%= @authorization.user.nome %>
</p>

<p>
  <strong>Room:</strong>
  <%= @authorization.room.title %>
</p>

<p>
  <strong>Date register:</strong>
  <%= @authorization.date_register %>
</p>

<p>
  <strong>Date expiration:</strong>
  <%= @authorization.date_expiration %>
</p>

<%= link_to 'Edit', edit_authorization_path(@authorization) %> |
<%= link_to 'Back', authorizations_path %>