config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :loans
  match 'loans/:id', controller: 'loans', action: 'devolver', via: 'post'
  resources :authorizations
  resources :rooms
  resources :users

  root 'loans#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CKeys</title>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">CRTKeys</a>
      </div>
      <% if @user_logado and (@user_logado.admin or @user_logado.servidor) %>
        <ul class="nav navbar-nav">
          <li><a href="<%= root_path %>">Empréstimos</a></li>
          <li><a href="<%= authorizations_path %>">Permissões</a></li>
          <li><a href="<%= users_path %>">Usuários</a></li>
          <li><a href="<%= rooms_path %>">Salas</a></li>
        </ul>
      <% end %>
      <% if @user_logado %>
          <div id="matriculatop">
            <%= @user_logado.nome_matricula%>
          </div>
          <div id="logouttop">
            <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-default" %>
          </div>
      <% else %>
          <div id="logouttop">
            <%= button_to 'Login', login_path, method: :get, class: "btn btn-primary btn-block" %>
          </div>
      <% end %>
    </div>

  </nav>
  <div class="tudo">
    <div id="flash">
      <% if flash[:alert] %>
        <p class="alert alert-danger"><%= flash[:alert] %></p>
      <% end %>
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= flash[:notice] %></p>
      <% end %>
    </div>
    <%= yield %>
  </div>
</body>
</html>